title: Arindam Debnath
description: "A brief description of your research interests."
url: "https://dovahkiin0022.github.io"
baseurl: ""
author:
  name: Arindam Debnath
  email: debnath@psu.edu
  github: dovahkiin0022 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
